### ISSUE TITLE
MapOutline Issues After ArcPro 2.8 Update 

### ISSUE THREAD

**Issue by gbvntura** [usgs/gems-tools-pro#10]
MapOutLines tool started presenting errors after updating ArcPro for its latest version. 
Below is the report after running the tool:

MapOutline
=====================
Parameters

SE longitude     -120.5
SE latitude     47.5
width (longitudinal extent)     0.04167
height (latitudinal extent)     0.04167
tic spacing     2.5
Is NAD27     true
output geodatabase     C:\Projects\Chiwaukum\Chiwaukum4SE.gdb
output coordinate system     PROJCS["NAD_1983_UTM_Zone_10N",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-123.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]
scratch workspace     C:\Projects\Chiwaukum\New Folder
=====================
Messages

Start Time: Friday, August 13, 2021 12:09:55 PM
Failed script MapOutline...
Traceback (most recent call last):
  File "C:\gems-tools-pro-2.4.8\Scripts\mapOutline_AGP2.py", line 20, in <module>
    checkVersion(versionString, rawurl, 'gems-tools-pro')
NameError: name 'checkVersion' is not defined

Failed to execute (MapOutline).
Failed at Friday, August 13, 2021 12:09:55 PM (Elapsed Time: 0.05 seconds)

**Comment by srmulcahy** [comment]
Same issue running ArcGIS Pro (v 2.8.2) and GeMS Pro 2.5.1

![InkedScreenshot 2021-09-13 161108_LI](https://user-images.githubusercontent.com/1202955/133169520-6276fc70-2e59-4390-9f08-daae19332814.jpg)
