### ISSUE TITLE
Zero-length, whitespace-only, or "<Null> Error

### ISSUE THREAD

**Issue by sdudash** [usgs/gems-tools-pro#12]
Hi, I continue to get this level 3 error despite the field having a null value. No matter how many times I try to fix the value in the field, I still get this error. Do you have any recommendations or fixes?  Thanks

**Comment by ethoms-usgs** [comment]
And this is a field where nulls are allowed? Are you calculating the field to be "<Null>", that is, a string that stores those characters or are you calculating the field as ```None``` using python in the field calculator?

https://support.esri.com/en/technical-article/000012852

**Comment by sdudash** [comment]
Yes, this is the  Description field in the DMU table. I actually didn't know about they "None" using the python calculator. This worked and I now have a level 3 compliant database!!!! Thanks for helping me with this user error.

**Comment by ethoms-usgs** [comment]
Excellent! Also, the Fix Strings tool should do that for all tables in the database.
