### ISSUE TITLE
Translate to Shapefiles

### ISSUE THREAD

**Issue by stub0035** [usgs/gems-tools-pro#14]
I'm trying to run the Translate to Shapefiles tool and it pops up this error.  I'm not sure if there is a setting I need to edit or if it's the tool. 

Start Time: Thursday, February 10, 2022 2:11:26 PM
This version of the tool is up to date
GeMS_TranslateToShape_AGP2.py, version of 18 July 2019
Traceback (most recent call last):
  File "J:\ArcGIS_scripts\GeMS\gems-tools-pro-2.5.2\gems-tools-pro-2.5.2\Scripts\GeMS_TranslateToShape_AGP2.py", line 447, in <module>
    arcpy.env.QualifiedFieldNames = False
AttributeError: 'GPEnvironment' object has no attribute 'QualifiedFieldNames'
Failed script Translate To Shapefiles...
Failed to execute (TranslateToShape).
Failed at Thursday, February 10, 2022 2:11:26 PM (Elapsed Time: 0.28 seconds)
 
Here is an image.
![image](https://user-images.githubusercontent.com/8901908/153492294-fbe98e7b-4027-421c-b10e-74c1e2ab8977.png)

I guess the image can' t go thru.

**Comment by chhalsted** [comment]
I just ran into the same error with the Translate to Shapefiles tool in ArcGIS Pro.  I had to change lines 447 and 448 from 

    arcpy.env.QualifiedFieldNames = False
    arcpy.env.overwriteoutput = True

to

    arcpy.env.qualifiedFieldNames = False
    arcpy.env.overwriteOutput = True

The tool ran fine after that.	
Could we get these changes into the next master version?  Thanks
