### ISSUE TITLE
MapUnitLines feature class is not an option in Create New Database tool

### ISSUE THREAD

**Issue by MnashUSGS** [usgs/gems-tools-pro#15]
I am attempting to create a new database for a GeMS-compliant map that I am practicing digitizing. 
After opening the Create New Database tool, there is no option to create a MapUnitLines feature class, which I need for dikes/bedding that is too thin to display with polygons. 

![NoMapUnitLines](https://user-images.githubusercontent.com/99765778/154150166-3b22dbc3-c2bd-4c04-89e8-902c4dce37ff.png)

MapUnitLines does not show up as an option. Is it added to the ArcPro version of GeMS Tools Pro 2.5.3 or gems-tools-master?

**Comment by ethoms-usgs** [comment]
Thanks for pointing that out! Just posted version 2.5.5 with a choice for MapUnitLines.
