### ISSUE TITLE
Error in Topology Check tool in ArcPro

### ISSUE THREAD

**Issue by MnashUSGS** [usgs/gems-tools-pro#16]
I attempted to run the Topology Check tool in ArcPro and it fails to run due to these errors. 

![TopologyCheckError](https://user-images.githubusercontent.com/99765778/154336064-f93582fd-ab3c-4417-9da9-04f67814bdf2.PNG)

Is this an error on my end or within the script? How may I fix it?

Thank you

**Comment by ethoms-usgs** [comment]
I am guessing you have some nulls in HierarchyKey? Is that true?

**Comment by MnashUSGS** [comment]
Oops. Yes I just discovered one. It's working now - sorry about that!
