### ISSUE TITLE
Issues with the use of headnotes in DMU

### ISSUE THREAD

**Issue by cgutierrez-01** [usgs/gems-tools-pro#18]
Hi Evan,

I just ran into two issues that seem to be related to the presence of headnotes in the DMU.

The first headnote issue is with the docx. to DMU tool (pro version). When headnotes are present, the hierarchy keys that get assigned are incorrect and do not keep the correct order of units (the first number in the hkey is not incrementing properly at each DMU-Heading2 record). When I remove the headnotes, the hkeys are generated properly. I wasn't sure if having multiple headnotes was the issue, so I removed all but the first headnote but the issue persisted. I have attached two csv files that have examples of the dmu table with headnotes and without so you can compare the hkeys.

The second headnote issue is related to the Validate Database tool (arcmap and pro versions), The GeMS documentation states that headnotes are to be stored in the Description field of the DMU table. The Docx. to DMU tool correctly loads the headnote into the Description field. However, the validation tool flags the empty/null Name field for the headnote record in the table as an error. It appears that the validation script accounts for special dmu units (ones that don't have a MapUnit value) to allow for nulls in certain fields that are required for units with MapUnit values, but a Name value is still required.

Any assistance you may be able to provide to help resolve these issues will be greatly appreciated.

Thanks!
Carlos

[dmu_with_headnotes.csv](https://github.com/usgs/gems-tools-pro/files/8188184/dmu_with_headnotes.csv)
[dmu_no_headnotes.csv](https://github.com/usgs/gems-tools-pro/files/8188185/dmu_no_headnotes.csv)

**Comment by ethoms-usgs** [comment]
Hi Carlos,
Apologies for not getting to this sooner. Outlook was putting notifications from github into my spam folder....

I am afraid I have to ask you to send me the csv files again. All of the HierarchyKeys were exported as dates! If you could, run the docx to DMU tool again but change line 219 from 

```newHKey.append(str(element).zfill(maxHKeyElementLength))```  to 
```newHKey.append(str(element).zfill(3))```

and then you will get hkey terms that have been zero-padded to 3 digits and nothing should confuse them with dates.

Meanwhile, I am thinking about your second question. I think I will have to add some code to see if ParagraphStyle is 'DMUHeadnote', which I have various problems with. It's kind of kludgy, but I guess as a workaround you could put 'headnote' in the Name field.

**Comment by cgutierrez-01** [comment]
Hi Evan,
Thanks for the follow-up. Here are the latest csv files. Let me know if you need any additional info or data. 

Yeah, I was thinking of just putting something in there to pass the validation. 'headnote' is a good suggestion. I think I'll go with that.

[dmu_with_headnotes.csv](https://github.com/usgs/gems-tools-pro/files/8321143/dmu_with_headnotes.csv)
[dmu_without_headnotes.csv](https://github.com/usgs/gems-tools-pro/files/8321145/dmu_without_headnotes.csv)
.

**Comment by ethoms-usgs** [comment]
Ok, one more thing. Can you send me the docx file?

**Comment by cgutierrez-01** [comment]
Sure, no problem. Here you go. One with the headnotes, one without.
