### ISSUE TITLE
Validate GDB - Feature classes with attachments

### ISSUE THREAD

**Issue by masseygeo** [usgs/gems-tools-pro#20]
Hello! We use several feature classes in our maps that contain attachments (Field locations with field photos, geochem locations with XRD spectrographs, etc). Unfortunately, the Validate Database (v2.7.1) doesn't seem to like attachments (or relationship classes?). Is this a bug with the script, or have I missed a GeMS requirement that specifies no attachments?

**Comment by masseygeo** [comment]
Oh, here's a screenshot of the result...
![image](https://user-images.githubusercontent.com/69476319/163396934-e368bb43-1c8b-46b0-ba0b-e1fc5c3101f1.png)

**Comment by masseygeo** [comment]
Roger that, That's what I've been doing (running the script after disabling attachments), but just want to make sure you're aware and/or I wasn't missing something obvious. Thanks for the reply though!

The error message should be below...not sure what happened above?
![Capture](https://user-images.githubusercontent.com/69476319/163433389-3bb584e2-c048-49da-9503-8bc3ee846897.PNG)

**Comment by ethoms-usgs** [comment]
Thanks, now I see it. 
Pretty sure I have seen this error before but I can't track the issue down. Have you, by chance, hidden the OBJECTID field in the view properties of that table or changed it's alias?

**Comment by masseygeo** [comment]
Negative on the OID. I may have possibly changed the alias on one of these, but I've tried the validation tool with all combinations of FCs with attachments and the script always fails. I'm happy to share my FGDB if you like?

**Comment by ethoms-usgs** [comment]
Sure, I would like to take a look.

**Comment by ethoms-usgs** [comment]
All right, I see the problem. I presume each of the tables with _ATTACH are created once the Add Attachment tool is run? In those tables, the objectid type field is called ATTACHMENTID. In the other case where your error was reported, the object id was called OBJECTID_1. 

I just posted a new release (v2.7.2) with changes to how the object id field is identified, no longer relying on the name. I ran your geodatabase with attachments through the validation tool and it ran correctly. Try it out and let me know.

**Comment by masseygeo** [comment]
Awesome. The new script woks perfectly! Thank you.

The one downside, is I now have to add a "_ID" field to the attachment tables to meet Level 3 GeMS compliance haha, but that can be easily automated with the Add Attachments GP tool.

Thanks for your quick response on this!

________________________________
Matthew A. Massey
Geologic Mapping Section
Kentucky Geological Survey
204 Mining and Mineral Resources Building
Lexington, KY 40506-0107
+1.859.323.0517 (office)

**Comment by ethoms-usgs** [comment]
Ah, good point. I just posted yet another release where tables with __ATTACH in the name will be ignored when looking for _ID fields. Not the best logic to go on name, but it does seem unlikely that someone would change the name that Arc assigns to attachment tables.
