### ISSUE TITLE
Symbol to RBG tool fails to locate the associated script. 

### ISSUE THREAD

**Issue by SMavorUSGS** [usgs/gems-tools-pro#27]
Issue: the Symbol to RGB tool fails with error message 000576: Script associated with this tool does not exist.

Workaround: I updated the script file location in the execution tab of the tool properties and it ran successfully. 

Suggested fix: I'm guessing this could be fixed with the relative pathnames setting.

**Comment by ethoms-usgs** [comment]
Thanks for finding that! Made the change and saved another release, v2.7.9
