### ISSUE TITLE
StationsID vs StationID

### ISSUE THREAD

**Issue by sdudash** [usgs/gems-tools-pro#30]
Hi, I have a database that is clean and validated from January of this year. I recently had to make some changes to the geology and am in the process of re-validating it. I keep getting an error:
Missing or mis-defined fields
    OrientationPoints, field StationsID is missing
    GeochronPoints, field StationsID is missing

The database does have these fields, but they are StationID vs StationsID.  I did fix this in the database and got a fully  compliant db, , but not sure if this is something that changed in the toolbox or not.
Thanks
Stephanie

Oh, also I was unable to validate the database and topology in ArcMap, but it worked fine in ArcPro. ArcMap and Catalog would crash when using the ArcMap toolbox.

**Comment by ethoms-usgs** [comment]
Yes, sorry about that. At some point the tool was verifying that the field was called StationID, but the GeMS document says it should be StationsID, so we corrected the mistake.
