### ISSUE TITLE
Validate Database Issue

### ISSUE THREAD

**Issue by mjohnsonIGWS** [usgs/gems-tools-pro#4]
Looks like there is an issue where one of the point feature attributes is being used for the check for all features and tables field check. See below the error I am getting:
    DataSources, field Type is missing
    DataSources, field StationID is missing
    DataSources, field MapUnit is missing
    DataSources, field Label is missing
    DataSources, field Symbol is missing
    DataSources, field PlotAtScale is missing
    DataSources, field LocationConfidenceMeters is missing
    DataSources, field LocationSourceID is missing
    DataSources, field DataSourceID is missing
    DataSources, field PhotoID is missing
    DataSources, field PhotoSubject is missing
    DataSources, field ViewDirection is missing
    DataSources, field ViewWidth is missing
    DataSources, field PhotoPoints_ID is missing

If I use the older toolbox I validate at level 3 with no errors or warnings. I have attached my HTML outputs.
[validationHTMLs.zip](https://github.com/usgs/gems-tools-pro/files/5983236/validationHTMLs.zip)

Thanks

**Comment by ethoms-usgs** [comment]
Thanks for letting us know. I will start looking at it today.

**Comment by ethoms-usgs** [comment]
Try again with v2.4.1 of the toolbox, or replace your copy of GeMS_ValidateDatabase_AGP2.py with the content from https://raw.githubusercontent.com/usgs/gems-tools-pro/master/Scripts/GeMS_ValidateDatabase_AGP2.py

I didn't find your errors exactly, but I did get an error that I think was from the same bug. The tool now writes out results that make sense, for me at least.

**Comment by mjohnsonIGWS** [comment]
Looks like that did the trick! Thanks Evan.
