### ISSUE TITLE
Create New Geodatabase tool fails

### ISSUE THREAD

**Issue by cheyennecox** [usgs/gems-tools-pro#6]
The Create New Geodatabase tool has worked successfully for me in the past, but when I run the tool now I get this error message: 

Traceback (most recent call last):
  File "C:\ArcFiles\GeMS\GeMS_ArcPro_Tools\gems-tools-pro-2.4.5\gems-tools-pro-2.4.5\Scripts\GeMS_CreateDatabase_AGP2.py", line 28, in <module>
    import copy       
NameError: name 'checkVersion' is not defined
 Failed to execute (CreateDatabase).

Does the tool need to be updated, or is there a simple fix I can make to the script? I am using the the most recent version of the tool (gems-tools-pro-2.4.5).

**Comment by ethoms-usgs** [comment]
No, that's the most recent version and it just ran fine for me. Can you comment out that line and see how far it runs?

**Comment by cheyennecox** [comment]
When I comment out line 28 and run the tool again I get this error message:

Traceback (most recent call last):
  File "C:\ArcFiles\GeMS\GeMS_ArcPro_Tools\gems-tools-pro-2.4.5\gems-tools-pro-2.4.5\Scripts\GeMS_CreateDatabase_AGP2.py", line 410, in <module>
    if sys.argv[6] == 'true':
  File "C:\ArcFiles_Cox\GeMS\GeMS_ArcPro_Tools\gems-tools-pro-2.4.5\gems-tools-pro-2.4.5\Scripts\GeMS_CreateDatabase_AGP2.py", line 345, in createDatabase
    geodatabase uniquely, and allow for multiple representations within a single feature class.
arcgisscripting.ExecuteError
 Failed to execute (CreateDatabase).

**Comment by ethoms-usgs** [comment]
Ah, sorry! I meant comment out line 32, where `checkVersion` is called. I was not clear, I apologize.

**Comment by cheyennecox** [comment]
That's okay! That seemed to do the trick. Thank you so much for the help!

**Comment by ethoms-usgs** [comment]
Ok, good. But the fact that one time before when you ran the tool it apparently executed past that line is odd. Could you try it again with the original script? The issue I am concerned about is that the `checkVersion` function is stored in an adjacent script file, `GeMS_utilityFunctions.py`. I don't think the Create Database script calls any other function from that file, but other tools definitely do. One other user has reported essentially the same error that you originally got and I haven't figured it out.

**Comment by cheyennecox** [comment]
Hmm that is odd. I just ran it with the original script, and it works for me now.

**Comment by ethoms-usgs** [comment]
Great! Let's just quietly walk away and hope to never speak of it again.
