### ISSUE TITLE
Attribute By Key Values script crashes

### ISSUE THREAD

**Issue by tfelger** [usgs/gems-tools-pro#8]
I'm getting the following error when I try to use the Attribute By Key Values script. It works in ArcMap.

Failed script Attribute By Key Values...
Traceback (most recent call last):
  File "C:\Data\ProjectData\GIS\DataModels\GeMS\ArcPro\gems-tools-pro-master_20210708\Scripts\GeMS_AttributeByKeyValues_AGP2.py", line 27, in <module>
    checkVersion(versionString, rawurl, 'gems-tools-pro')
NameError: name 'checkVersion' is not defined

Failed to execute (AttributeByKeyValues).

![image](https://user-images.githubusercontent.com/52179206/125100039-84ebf980-e08d-11eb-9376-5f5750ee2b43.png)

**Comment by ethoms-usgs** [comment]
Ah, indeed. The function was being called before being imported. See v2.4.8. Should be good now.

**Comment by tfelger** [comment]
That did the trick - Thanks!
